version: "3.9"

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    redis:
        image: redis:3.2-alpine
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
volumes:
    redis_data:
