# Generated by Django 3.1.5 on 2021-01-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
                ('banner_img', models.CharField(max_length=200)),
                ('flairs', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=75)),
                ('creation_date', models.DateTimeField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_count', models.IntegerField(blank=True, null=True)),
                ('current_count', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subreddit')),
            ],
        ),
    ]
