# Generated by Django 3.1.5 on 2021-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210110_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='banner_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='flairs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
