# Generated by Django 3.1.5 on 2021-01-10 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210110_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriberhistory',
            options={'verbose_name': 'Subscriber History', 'verbose_name_plural': 'Subscriber History'},
        ),
        migrations.RenameField(
            model_name='subscriberhistory',
            old_name='current_count',
            new_name='subscriber_count',
        ),
        migrations.RemoveField(
            model_name='subscriberhistory',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='subscriberhistory',
            name='previous_count',
        ),
        migrations.AddField(
            model_name='subscriberhistory',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
